# Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy webapp \
          --image gcr.io/$PROJECT_ID/webapp:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --service-account webapp-deployer@$PROJECT_ID.iam.gserviceaccount.com \
          --add-cloudsql-instances=${_CLOUDSQL_INSTANCE} \
          --set-env-vars "NODE_ENV=production,INSTANCE_CONNECTION_NAME=${_CLOUDSQL_INSTANCE},DB_NAME=Clearway_Cyber_db,DB_USER=root"