steps:
  # Step 1: Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/**webapp**:$COMMIT_SHA', '.']  # Ensure name is 'webapp'
  
  # Step 2: Push  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/**webapp**:$COMMIT_SHA']  # Ensure name is 'webapp'

images:
  - 'gcr.io/$PROJECT_ID/**webapp**:$COMMIT_SHA'  # Ensure name is 'webapp'